### ISSUE TITLE
 Cannot read property 'compactionInterval' of undefined

### ISSUE THREAD

**Issue by organic-scholar** [fortunejs/fortune-nedb#1]
``` javascript
var fortune = require('fortune');
var nedbAdapter = require('fortune-nedb');
var http = require('http');

var store = fortune.create({
    adapter: {
        type: nedbAdapter,
    }
});
```

 Following code throws error Cannot read property 'compactionInterval' of undefined

**Comment by gr0uch** [comment]
I updated dependencies in this commit https://github.com/fortunejs/fortune-nedb/commit/f015eb89c96ff65431e14a5496da7ea60326cec2, and the tests pass. Can you confirm that it works for you?

**Comment by organic-scholar** [comment]
Thanks its working now.
