### ISSUE TITLE
Remove Babel

### ISSUE THREAD

**Issue by gr0uch** [fortunejs/fortune-nedb#2]
Babel considered harmful.

**Comment by coderofsalvation** [comment]
why is it in there actually?

**Comment by gr0uch** [comment]
This was pre-iojs merge, so basically Node had no ES6 features without turning on flags.

**Comment by gr0uch** [comment]
Done in commit https://github.com/fortunejs/fortune-nedb/commit/fbb18cb0e719dc5a7bda012c82b3c38685fffa82.
