### ISSUE TITLE
Type-specific paths

### ISSUE THREAD

**Issue by IonicaBizau** [fortunejs/fortune-nedb#3]
I would like to have a way to specify the paths for each `db` file, depending on the type. Currently all the types are stored in one directory.

**Comment by gr0uch** [comment]
What is the motivation for this? AFAIK some DBs only let you specify a directory, and they manage filenames, for example MongoDB does this.

**Comment by IonicaBizau** [comment]
I was just wondering if I can keep my current directory structure, but I got it. :+1:
