### ISSUE TITLE
Generate URI safe ids?

### ISSUE THREAD

**Issue by zchrykng** [fortunejs/fortune-nedb#5]
Currently the function [here](https://github.com/fortunejs/fortune-nedb/blob/master/lib/helpers.js#L121-L131) generates random ids that include characters that have special meaning in URIs, which causes problems with REST apis. I realize that they should probably just be encoded, but mainly commenting because it changes the default behaviour of nedb [see here](https://github.com/louischatriot/nedb/blob/master/lib/customUtils.js#L4-L17).

**Comment by gr0uch** [comment]
I guess it could use the default ID generation. PR welcome.

**Comment by zchrykng** [comment]
No big deal. Dug into my problems a bit more and found that the ids were being properly encoded in the on the server end but then not being encoded properly when used for requests. Got the client library patched and everything is good to go.

😄
